# Generated by Django 3.2.5 on 2021-08-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_signoutentry_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signinentry',
            options={'ordering': ['-date', 'time']},
        ),
    ]
